### ISSUE TITLE
DataJpaTest, how to execute separatly ?

### ISSUE THREAD

**Issue by M3lkior** [snicoll-demos/cfp-example#2]
Hello Stephane,

Actually, when running mvn clean test (for exemple on your project), `SubmissionTest` also execute UserTest (and no SpringContext was loaded for UserTest) : 

`

2017-04-25 11:41:53.437  INFO 9368 --- [           main] com.example.cfp.domain.SubmissionTest    : Starting SubmissionTest on MacBook-.local with PID 9368 (started by melkior in /Users/melkior/Documents/Workplaces/cfp-example)

... 

Running com.example.cfp.domain.UserTest

...

`
- Why com.example.cfp.domain.UserTest was run inside SubmissionTest (even if it contains is own @DataJpaTest annotation )?
- Here is a way to independly execute DataJpaTest i.e loading spring context for each com.example.cfp.domain.SubmissionTest and com.example.cfp.domain.UserTest without execute all of theses tests in each Test class ?
- How can i load a different context (for exemple a different liquibase changelog entry-point) for each test ? (by profile or @TestPropertySource(properties = "liquibase.change-log=classpath:my.db.changelog-test.xml", even if this annotation is designed for integration tests and not for jpa tests ?)

I work on a project containing at least 15 @DataJpaTest and all tests was executed for each test class which is redundant and take extra time ...

Thanks for your answer.

**Comment by snicoll** [comment]
Sorry for the late reply but I forgot to watch the repo. 

> SubmissionTest also execute UserTest 

I don't believe it does that. If you want to execute one test on the command line you could do `mvn test -Dtest= SubmissionTest`. I did that and only `SubmissionTest` ran.

If you're still affected, please create a StackOverflow question.
